In [1]:
from sklearn.datasets import load_digits

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = load_digits()

In [4]:
print(data.DESCR)

.. _digits_dataset:

Optical recognition of handwritten digits dataset
--------------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 1797
    :Number of Attributes: 64
    :Attribute Information: 8x8 image of integer pixels in the range 0..16.
    :Missing Attribute Values: None
    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
    :Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
https://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are counted in each blo

In [5]:
features = data.data
target = data.target

features.shape,target.shape

((1797, 64), (1797,))

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(features, target, train_size = 0.6, random_state = 3)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1078, 64)
(719, 64)
(1078,)
(719,)


In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
my_model = LogisticRegression()

In [10]:
my_model.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [11]:
preds = my_model.predict(X_test)

In [12]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [13]:
print(accuracy_score(y_test, preds))

0.9582753824756607


In [14]:
print(confusion_matrix(y_test, preds))

[[74  0  0  0  1  0  0  0  0  0]
 [ 0 72  0  0  0  0  0  0  2  1]
 [ 0  1 77  0  0  0  0  0  0  0]
 [ 0  0  2 66  0  0  0  0  1  0]
 [ 0  4  0  0 79  0  1  1  1  0]
 [ 0  1  0  0  1 60  0  0  0  2]
 [ 0  1  0  0  0  1 55  0  1  0]
 [ 0  0  0  1  0  0  0 73  2  0]
 [ 0  1  0  0  0  1  0  0 66  0]
 [ 0  0  0  0  1  1  0  0  1 67]]


In [15]:
from sklearn.decomposition import PCA

Initially I have 64 dimensions. Now I want to bring it down to 4 dimensions

In [16]:
# pca = PCA(n_components=4) # Defining how many dimension (no of component) we want
pca = PCA(n_components=0.7) #Explicitly mentioning the fraction the information

In [17]:
pca.fit(X_train)

PCA(n_components=0.7)

In [18]:
#return the number of component based on the portion supplied above
pca.explained_variance_ratio_

array([0.14924092, 0.13473079, 0.1156578 , 0.08302537, 0.06011606,
       0.05032773, 0.04284684, 0.03556855, 0.03294894])

In [19]:
#The % of the data captured
np.sum(pca.explained_variance_ratio_) 

0.7044629853078586

In [20]:
#Transform using the PCA
X_train_transformed = pca.transform(X_train)
X_test_transformed = pca.transform(X_test)

In [21]:
X_train_transformed.shape, X_test_transformed.shape

((1078, 9), (719, 9))

In [22]:
pca.inverse_transform(X_train_transformed).shape #Get  the original data

(1078, 64)

In [23]:
my_model.fit(X_train_transformed,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [24]:
preds = my_model.predict(X_test_transformed)

In [25]:
# Percentage of Accuracy
print(accuracy_score(y_test, preds))

0.9262865090403338


TASK

1. Perform scaling on cancer data and do the modelling. Check for difference without scaling and with scaling
2. Perform PCA with components such that its capturing atleast 50% of the variance and do the modelling

In [26]:
from sklearn.datasets import load_breast_cancer

In [27]:
breast_cancer_data = load_breast_cancer()

In [28]:
print(breast_cancer_data.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [29]:
features = breast_cancer_data.data
target = breast_cancer_data.target

features.shape,target.shape

((569, 30), (569,))

In [30]:
#Convert to Dataframe
features = pd.DataFrame(breast_cancer_data.data, columns=breast_cancer_data.feature_names)
target = pd.DataFrame(breast_cancer_data.target, columns=['Target'])

In [31]:
features.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [32]:
target.head()

Target
0       0
1       0
2       0
3       0
4       0

#Perform scaling on cancer data

In [33]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder

In [34]:
std_scale_mean_peri = StandardScaler()
std_scale_mean_area = StandardScaler()
std_scale_worst_area = StandardScaler()

std_scale_mean_peri.fit(features[['mean perimeter']])
std_scale_mean_area.fit(features[['mean area']])
std_scale_worst_area.fit(features[['worst perimeter']])

StandardScaler()

In [35]:
print('Mean of the Columns')
print(std_scale_mean_peri.mean_)
print(std_scale_mean_area.mean_)
print(std_scale_worst_area.mean_)
print(" ")
print("Scale of the Columns")
print(std_scale_mean_peri.scale_)
print(std_scale_mean_area.scale_)
print(std_scale_worst_area.scale_)

Mean of the Columns
[91.96903339]
[654.88910369]
[107.26121265]
 
Scale of the Columns
[24.27761929]
[351.60475406]
[33.57300157]


In [36]:
#data['Salary_standard_scaled'] = std_scale_sal.transform(data[['Salary']])
#data
features['mean_perimeter_std_scaled'] = std_scale_mean_peri.transform(features[['mean perimeter']])
features['mean_area_std_scaled'] = std_scale_mean_area.transform(features[['mean area']])
features['worst_area_std_scaled'] = std_scale_worst_area.transform(features[['worst perimeter']])

features.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst area  worst smoothness  \
0                 0.07871  ...      2019.0            0.1622   
1                 0.05667  ...      1956.0            0.1238   
2                 0.05999  ...      1709.0            0.1444   
3                 0.09744  ...       567.7            0.2098   
4                 0.05883  ...      1575.0            0.1374   

   worst compactness  worst concavity  worst concave points  worst symmetry  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   worst fractal dimension  mean_perimeter_std_scaled  mean_area_std_scaled  \
0                  0.11890                   1.269934              0.984375   
1                  0.08902                   1.685955              1.908708   
2                  0.08758                   1.566503              1.558884   
3                  0.17300                  -0.592687             -0.764464   
4                  0.07678                   1.776573              1.826229   

   worst_area_std_scaled  
0               2.303601  
1               1.535126  
2               1.347475  
3              -0.249939  
4               1.338539  

[5 rows x 33 columns]

In [37]:
features.describe()

mean radius  mean texture  mean perimeter    mean area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       mean symmetry  mean fractal dimension  ...   worst area  \
count     569.000000              569.000000  ...   569.000000   
mean        0.181162                0.062798  ...   880.583128   
std         0.027414                0.007060  ...   569.356993   
min         0.106000                0.049960  ...   185.200000   
25%         0.161900                0.057700  ...   515.300000   
50%         0.179200                0.061540  ...   686.500000   
75%         0.195700                0.066120  ...  1084.000000   
max         0.304000                0.097440  ...  4254.000000   

       worst smoothness  worst compactness  worst concavity  \
count        569.000000         569.000000       569.000000   
mean           0.132369           0.254265         0.272188   
std            0.022832           0.157336         0.208624   
min            0.071170           0.027290         0.000000   
25%            0.116600           0.147200         0.114500   
50%            0.131300           0.211900         0.226700   
75%            0.146000           0.339100         0.382900   
max            0.222600           1.058000         1.252000   

       worst concave points  worst symmetry  worst fractal dimension  \
count            569.000000      569.000000               569.000000   
mean               0.114606        0.290076                 0.083946   
std                0.065732        0.061867                 0.018061   
min                0.000000        0.156500                 0.055040   
25%                0.064930        0.250400                 0.071460   
50%                0.099930        0.282200                 0.080040   
75%                0.161400        0.317900                 0.092080   
max                0.291000        0.663800                 0.207500   

       mean_perimeter_std_scaled  mean_area_std_scaled  worst_area_std_scaled  
count               5.690000e+02          5.690000e+02           5.690000e+02  
mean               -1.272171e-16         -1.900452e-16          -4.015534e-16  
std                 1.000880e+00          1.000880e+00           1.000880e+00  
min                -1.984504e+00         -1.454443e+00          -1.693361e+00  
25%                -6.919555e-01         -6.671955e-01          -6.895783e-01  
50%                -2.359800e-01         -2.951869e-01          -2.859802e-01  
75%                 4.996769e-01          3.635073e-01           5.402790e-01  
max                 3.976130e+00          5.250529e+00           4.287337e+00  

[8 rows x 33 columns]

#Modelling

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
X_train, X_test, y_train, y_test = train_test_split(features, target, train_size = 0.6, random_state = 3)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(341, 33)
(228, 33)
(341, 1)
(228, 1)


In [40]:
from sklearn.linear_model import LogisticRegression

In [41]:
my_model = LogisticRegression()

In [42]:
my_model.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [43]:
preds = my_model.predict(X_test)

In [44]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [45]:
# 94% Accuracy with ALL components and some scaled
print(accuracy_score(y_test, preds))

0.9473684210526315


In [46]:
print(confusion_matrix(y_test, preds))

[[ 73   7]
 [  5 143]]


# Dimensionality Reductions With PCA

Initially I have 64 dimensions. Now I want to bring it down to 4 dimensions

In [47]:
#pca = PCA(n_components=4) #Stating the number of component
# Select 40% of component
pca = PCA(n_components=0.4)

In [48]:
pca.fit(X_train)

PCA(n_components=0.4)

In [49]:
# % of data the selected component represents
pca.explained_variance_ratio_

array([0.97854847])

In [50]:
np.sum(pca.explained_variance_ratio_)

0.9785484744517106

In [51]:
X_train_transformed = pca.transform(X_train)
X_test_transformed = pca.transform(X_test)

In [52]:
X_train_transformed.shape, X_test_transformed.shape

((341, 1), (228, 1))

In [53]:
pca.inverse_transform(X_train_transformed).shape

(341, 33)

In [54]:
my_model.fit(X_train_transformed,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [55]:
preds = my_model.predict(X_test_transformed)

In [56]:
# 91% Accuracy prediction with just 4 components
print(accuracy_score(y_test, preds))

0.9166666666666666
