In [45]:
import pandas as pd
import numpy as np

In [46]:
import matplotlib.pyplot as plt
%matplotlib inline

In [47]:
dataframe_train = pd.read_csv('train.csv')
dataframe_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [48]:
dataframe_train.shape

(891, 12)

In [49]:
dataframe_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [50]:
dataframe_train.Cabin.unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

In [51]:
dataframe_train.Survived.value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [52]:
dataframe_train.Sex.value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [53]:
dataframe_train.Embarked.value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [54]:
dataframe_train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [55]:
dataframe_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [56]:
# All these columns seems to be irrelevant. Though you can add SibSp and Parch in your data.
columns_to_drop = ['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin']

In [57]:
dataframe_train = dataframe_train.drop(columns_to_drop, axis = 1)
dataframe_train.head()

Survived  Pclass     Sex   Age     Fare Embarked
0         0       3    male  22.0   7.2500        S
1         1       1  female  38.0  71.2833        C
2         1       3  female  26.0   7.9250        S
3         1       1  female  35.0  53.1000        S
4         0       3    male  35.0   8.0500        S

In [58]:
dataframe_train[dataframe_train['Age'].isna()]

Survived  Pclass     Sex  Age     Fare Embarked
5           0       3    male  NaN   8.4583        Q
17          1       2    male  NaN  13.0000        S
19          1       3  female  NaN   7.2250        C
26          0       3    male  NaN   7.2250        C
28          1       3  female  NaN   7.8792        Q
..        ...     ...     ...  ...      ...      ...
859         0       3    male  NaN   7.2292        C
863         0       3  female  NaN  69.5500        S
868         0       3    male  NaN   9.5000        S
878         0       3    male  NaN   7.8958        S
888         0       3  female  NaN  23.4500        S

[177 rows x 6 columns]

In [59]:
# Smart way of replacing null values in age column by looking into Pclass as reference column
dataframe_train.groupby('Pclass').mean()[['Age']]

Age
Pclass           
1       38.233441
2       29.877630
3       25.140620

In [60]:
def age_approx(cols):
    Age = cols[0]
    Pclass = cols[1]
    
    if pd.isnull(Age):
        if Pclass == 1 :
            return 39
        elif Pclass == 2:
            return 30
        else:
            return 24
    else:
        return Age

In [61]:
dataframe_train['Age'] = dataframe_train[['Age','Pclass']].apply(age_approx, axis = 1)
dataframe_train

Survived  Pclass     Sex   Age     Fare Embarked
0           0       3    male  22.0   7.2500        S
1           1       1  female  38.0  71.2833        C
2           1       3  female  26.0   7.9250        S
3           1       1  female  35.0  53.1000        S
4           0       3    male  35.0   8.0500        S
..        ...     ...     ...   ...      ...      ...
886         0       2    male  27.0  13.0000        S
887         1       1  female  19.0  30.0000        S
888         0       3  female  24.0  23.4500        S
889         1       1    male  26.0  30.0000        C
890         0       3    male  32.0   7.7500        Q

[891 rows x 6 columns]

In [62]:
dataframe_train.isna().sum()

Survived    0
Pclass      0
Sex         0
Age         0
Fare        0
Embarked    2
dtype: int64

In [63]:
dataframe_train.dropna(inplace = True)
dataframe_train.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
Fare        0
Embarked    0
dtype: int64

In [64]:
dataframe_train.dtypes

Survived      int64
Pclass        int64
Sex          object
Age         float64
Fare        float64
Embarked     object
dtype: object

In [65]:
# Both the columns are ordinal variables so applying one hot encoding
dataframe_train_one_hot = pd.get_dummies(dataframe_train, columns = ['Sex','Embarked'])

In [66]:
dataframe_train_one_hot

Survived  Pclass   Age     Fare  Sex_female  Sex_male  Embarked_C  \
0           0       3  22.0   7.2500           0         1           0   
1           1       1  38.0  71.2833           1         0           1   
2           1       3  26.0   7.9250           1         0           0   
3           1       1  35.0  53.1000           1         0           0   
4           0       3  35.0   8.0500           0         1           0   
..        ...     ...   ...      ...         ...       ...         ...   
886         0       2  27.0  13.0000           0         1           0   
887         1       1  19.0  30.0000           1         0           0   
888         0       3  24.0  23.4500           1         0           0   
889         1       1  26.0  30.0000           0         1           1   
890         0       3  32.0   7.7500           0         1           0   

     Embarked_Q  Embarked_S  
0             0           1  
1             0           0  
2             0           1  
3             0           1  
4             0           1  
..          ...         ...  
886           0           1  
887           0           1  
888           0           1  
889           0           0  
890           1           0  

[889 rows x 9 columns]

In [67]:
dataframe_train_one_hot.columns

Index(['Survived', 'Pclass', 'Age', 'Fare', 'Sex_female', 'Sex_male',
       'Embarked_C', 'Embarked_Q', 'Embarked_S'],
      dtype='object')

In [68]:
X = dataframe_train_one_hot[['Pclass', 'Age', 'Fare', 'Sex_female', 'Sex_male',
       'Embarked_C', 'Embarked_Q', 'Embarked_S']]
y = dataframe_train_one_hot['Survived']

In [69]:
X.shape,y.shape

((889, 8), (889,))

In [80]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y)

In [81]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((666, 8), (223, 8), (666,), (223,))

In [82]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

age_mm_scaler = MinMaxScaler()
fare_std_scaler = StandardScaler()

# X_train['Age'] = age_mm_scaler.fit_transform(X_train[['Age']])
X_train['Fare'] = fare_std_scaler.fit_transform(X_train[['Fare']])
X_train

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys


Pclass   Age      Fare  Sex_female  Sex_male  Embarked_C  Embarked_Q  \
418       2  30.0 -0.415961           0         1           0           0   
115       3  21.0 -0.525273           0         1           0           0   
447       1  34.0 -0.124103           0         1           0           0   
171       3   4.0 -0.068639           0         1           0           1   
379       3  19.0 -0.528503           0         1           0           0   
..      ...   ...       ...         ...       ...         ...         ...   
832       3  24.0 -0.540260           0         1           1           0   
753       3  23.0 -0.525902           0         1           0           0   
402       3  21.0 -0.484348           1         0           0           0   
540       1  36.0  0.833320           1         0           0           0   
101       3  24.0 -0.525902           0         1           0           0   

     Embarked_S  
418           1  
115           1  
447           1  
171           0  
379           1  
..          ...  
832           0  
753           1  
402           1  
540           1  
101           1  

[666 rows x 8 columns]

In [83]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()

In [84]:
logreg.fit(X_train,y_train)

/usr/local/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [85]:
logreg.coef_, logreg.intercept_

(array([[-1.261708  , -0.03726401, -0.08849846,  1.19246397, -1.20672365,
          0.23788119,  0.05259838, -0.30473925]]),
 array([4.00755368]))

In [90]:
X_test['Fare'] = fare_std_scaler.transform(X_test[['Fare']])

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [91]:
y_pred = logreg.predict(X_test)
y_pred

array([0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1])

In [87]:
#Prediciting Probabilities
#[np.argmax(logreg.predict_proba(X_test)[i]) for i in range(len(X_test))]

In [88]:
from sklearn import metrics

In [89]:
metrics.accuracy_score(y_test, y_pred)

0.7354260089686099

In [35]:
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.78      0.86      0.82       125
           1       0.80      0.69      0.74        98

    accuracy                           0.79       223
   macro avg       0.79      0.78      0.78       223
weighted avg       0.79      0.79      0.79       223

