In [1]:
from sklearn.datasets import load_digits

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = load_digits()

In [4]:
print(data.DESCR)

.. _digits_dataset:

Optical recognition of handwritten digits dataset
--------------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 1797
    :Number of Attributes: 64
    :Attribute Information: 8x8 image of integer pixels in the range 0..16.
    :Missing Attribute Values: None
    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
    :Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
https://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are counted in each blo

In [6]:
features = data.data
target = data.target

features.shape,target.shape

((1797, 64), (1797,))

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(features, target, train_size = 0.6, random_state = 3)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1078, 64)
(719, 64)
(1078,)
(719,)


In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
my_model = LogisticRegression()

In [11]:
my_model.fit(X_train,y_train)

/usr/local/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [12]:
preds = my_model.predict(X_test)

In [13]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [14]:
print(accuracy_score(y_test, preds))

0.9582753824756607


In [15]:
print(confusion_matrix(y_test, preds))

[[74  0  0  0  1  0  0  0  0  0]
 [ 0 72  0  0  0  0  0  0  2  1]
 [ 0  1 77  0  0  0  0  0  0  0]
 [ 0  0  2 66  0  0  0  0  1  0]
 [ 0  4  0  0 79  0  1  1  1  0]
 [ 0  1  0  0  1 60  0  0  0  2]
 [ 0  1  0  0  0  1 55  0  1  0]
 [ 0  0  0  1  0  0  0 73  2  0]
 [ 0  1  0  0  0  1  0  0 66  0]
 [ 0  0  0  0  1  1  0  0  1 67]]


In [16]:
from sklearn.decomposition import PCA

Initially I have 64 dimensions. Now I want to bring it down to 4 dimensions

In [37]:
pca = PCA(n_components=0.7)

In [38]:
pca.fit(X_train)

PCA(n_components=0.7)

In [39]:
pca.explained_variance_ratio_

array([0.14924092, 0.13473079, 0.1156578 , 0.08302537, 0.06011606,
       0.05032773, 0.04284684, 0.03556855, 0.03294894])

In [40]:
np.sum(pca.explained_variance_ratio_)

0.7044629853078586

In [41]:
X_train_transformed = pca.transform(X_train)
X_test_transformed = pca.transform(X_test)

In [42]:
X_train_transformed.shape, X_test_transformed.shape

((1078, 9), (719, 9))

In [43]:
pca.inverse_transform(X_train_transformed).shape

(1078, 64)

In [44]:
my_model.fit(X_train_transformed,y_train)

/usr/local/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [45]:
preds = my_model.predict(X_test_transformed)

In [46]:
print(accuracy_score(y_test, preds))

0.9262865090403338


TASK

1. Perform scaling on cancer data and do the modelling. Check for difference without scaling and with scaling
2. Perform PCA with components such that its capturing atleast 50% of the variance and do the modelling

In [47]:
from sklearn.datasets import load_breast_cancer